### ISSUE TITLE
Several fixes for indicator->numerator screen

### ISSUE THREAD

**Issue by Markionium** [dhis2/maintenance-app#202]
- [ ] Indicator numerator element labels are flowing into each other #172
- [ ] Indicator numerator description is hidden on 768 px screens #184
- [ ] Window movement during numerator/denominator configuration #67
- [ ] Formula editor more dynamic #122
- [x] IndicatorExpression manager 50+ programs dropdown does not show scrollbar #150
