### ISSUE TITLE
Add tracker attribute and related objects to maintenance app

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#227]
Add CRUD operations for the following tracker related objects.

Objects
---
- Attribute
- Attribute group
- Relationship type
- Tracked entity

These objects can currently be found in the Program module.

- [x] Add basic fields

__Tracked Entity Attribute__
- [ ] Add `unique` skip logic
- [x] ~~Check if disabling `searchScope` when confidential is checked is still relevant~~
- [x] ~~Check if `searchScope` is still relevant.~~
- [ ] Implement skip logic contained in `attribute.js`
- [x] Have encryption status be exposed through the api

**Comment by Markionium** [comment]
@abyot Is the `trackedEntity` property on `trackedEntityAttribute` used anywhere? It seems the demo database does not contain any examples where the `trackedEntityAttribute` has a `trackedEntity` value.

There is some logic in the update form for `trackedEntityAttribute` and i'm trying to understand what it should do.

**Comment by Markionium** [comment]
@ abyot What is `Manage attributes for visit schedule` used for? I'm trying to understand what/where it's used.
![image](https://cloud.githubusercontent.com/assets/2134901/17967249/5130340e-6ac6-11e6-8ecb-cd3a9b97d2e0.png)

**Comment by abyot** [comment]
@Markionium the trackedEntity property of trackedEntityAttribute is used only when valueType is set to TRACKER_ASSOCIATE. This is to limit the domain of tracked entity instances that a tracked entity attribute can have as a it's value.

Manage attributes for visit schedule is no longer required. The idea was to decide which of the attributes can appear on "Visit Schedule Tabular Report". But since we can allow the user to dynamically decide on the columns, this is not required anymore...

**Comment by jijukjose** [comment]
Doc link - https://github.com/dhis2/dhis2-docs/issues/158
